version: "3.8"

services:
  db_service:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db_service

  api:
    build: .
    command: uvicorn app.main:app --reload --port=8000 --host=0.0.0.0
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db_service
