"""added total

Revision ID: 5dd9b720bbb5
Revises: b56e05651540
Create Date: 2023-07-28 22:17:37.898424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd9b720bbb5'
down_revision = 'b56e05651540'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'total')
    # ### end Alembic commands ###
